### ISSUE TITLE
Query Does not update after mutation on a pushed screen

### ISSUE THREAD

**Issue by vmwsree** [zino-app/graphql-flutter#129]
![bug](https://user-images.githubusercontent.com/1706515/47592724-1b396900-d992-11e8-94da-2b4def0b7160.gif)
**Describe the bug**
I have a profile page where each item is rendered with Query but the edit button takes to a new Screen Where a mutation is successfully executed to update the value. but once this screen is poped the older screen query does not hit server rather it re renders older values. How can I tell the query to refresh from server.

**Expected behavior**
I expect the query to be updated after the mutation is ran either through api or cache or the developer has power to invoke , is there any example that I can look ,which solves this problem.
**Screenshots**
https://gfycat.com/FoolhardyShamelessBubblefish

**Smartphone (please complete the following information):**

**Additional context**
The values are updated if I do a hard reload

**Comment by HofmannZ** [comment]
@vmwsree When you pop a screen the old screen does not get re-rendered thus the query does not get refetched. We are looking to add a refetch option the the query, but right now you can fix it by polling the query.

**Comment by sjmcdowall** [comment]
Option 2 -- which is a bit more complex - is to put all the data in question into a ScopedModel and use a ScopedModelDescendt in the main list screen and populate the screen from that (obviously use the Query to build the data) .. then in the Edit/Add screen update the data that's in the ScopedModel .. this should cause an update to the List since ScopedModelDescrendent is reactive on changes within it.. 

In reality you could maybe cheat -- and just have some "trigger" in ScopedModel that is used within the build() of the List .. and have the Edit/Add screen update the trigger .. which should (?) cause the build() below ScopedModelDescendent to run agian.. if your Query is below him .. it should retrigger the query .. of course you'll need to make sure you have a Fetchoption of either NetworkOnly or CacheNetwork for it to actually show ..??  

Just some random ideas..

**Comment by karbal** [comment]
I found the issue is in the Query Widget, Should comment in The lines 67 and 69 the Function didUpdateWidget, I think that we must always regenerate the widget.
```
 void didUpdateWidget(Query oldWidget) {
    super.didUpdateWidget(oldWidget);

    // if (!observableQuery.options.areEqualTo(_options)) {
      _initQuery();
    // }
  }
```

**Comment by degroote22** [comment]
> I found the issue is in the Query Widget, Should comment The lines 67 and 69 in the Function didUpdateWidget, I think that we must always regenerate the widget.
> 
> ```
>  void didUpdateWidget(Query oldWidget) {
>     super.didUpdateWidget(oldWidget);
> 
>     // if (!observableQuery.options.areEqualTo(_options)) {
>       _initQuery();
>     // }
>   }
> ```

This is kind resource-wasteful, I think.
It would be better to have the queries subscribe to the cache and have the cache notify queries of changes.
I'm not sure how to do it in Dart, though. (Dart noob here)

**Comment by micimize** [comment]
#199 adds/leverages `rebroadcastQueries`, which will solve this problem.
This is similar enough to #190 that I'm going to close in favor of that one

**Comment by insidewhy** [comment]
@vmwsree Did you ever manage to fix this? We're having the same issue with the latest version and even though we get logs from our `builder` method showing the new data, the widget still shows stale data.

**Comment by vincenzopalazzo** [comment]
HI @insidewhy,

The issue is very old, maybe can you tell us what is your lib version, and if you have not yet updated to the last version in beta 5.0.1-beta.1 please do.

In addition, if you can produce an example like the one inside this issue, can you consider opening an issue? thanks

**Comment by insidewhy** [comment]
In the end I tracked it down to an issue with `showDialogue` sorry it wasn't to do with this.

**Comment by alexboulay** [comment]
I'm sorry for commenting on this very old issue but I am facing the exact problem illustrated in the original question. When I pop my screen, the widget does not get re-rendered and never gets to read the newly updated cache. Is there an additional thing I should do when popping the screen? 

It works fine when I update the cache while being on the screen in question. The problem is when I update the cache on a pushed screen.
