### ISSUE TITLE
Synchronously return data from cache if available

### ISSUE THREAD

**Issue by smkhalsa** [zino-app/graphql-flutter#290]
I'd like to use the [Hero](https://flutter.dev/docs/development/ui/animations/hero-animations) widget when navigating between screens. However, it requires that the shared widget be available upon first paint on both screens. The data property is currently always null on the initial render, even if results (or partial normalized results) are available in the cache.

I propose that we adjust the client so that it includes data from the cache synchronously on first render, even if it's incomplete for the given query.

**Comment by micimize** [comment]
Thinking out loud:
The first way I can think of to do this is to move `initialData`handling into `ObservableQuery` so that the widget looks something like 
```dart
    return StreamBuilder<QueryResult>(
      initialData: observableQuery.latestResult //...
```
Which can then decide if it's loading, optimistic, etc.

* There's already a `ObservableQuery.previousResult`, which we would privatize
* add `get latestResult => _previousResult ?? QueryResult(loading: true)`
* break `addOptimisticQueryResult` and `_addEagerCacheResult` into a synchronous process that completes before the mostly async `fetchQuery` logic

That way by the end of a synchronous call to `watchQuery`, `latestResult` will always have any `cacheFirst` results if present.

**Comment by micimize** [comment]
Okay, yeah we can just break that logic into `eagerlyResolveQuery` and then call it again on `fetchQuery` if the options have changed
