### ISSUE TITLE
How can I use graphql-flutter with  MultiProvider

### ISSUE THREAD

**Issue by jerryzhoujw** [zino-app/graphql-flutter#339]
```dart

Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AuthState>.value(
          notifier: AuthState(),
        ),
        // GraphQLProvider(child: _client,),              //<-- error
        ChangeNotifierProvider<GraphQLClient>.value(      //<-- error
          notifier: _client,
        ),
        // ValueNotiferProvider.val
      ],
      child: MaterialApp(
           ....
      ),
    );
  }
}
```

How can I do this above?  Just want to make auth server & graphQL service together.

I was plan to separate multi service(assume include `Auth`, `graphQL`, `store` and so on ) use `MultiProvider`, so I'd like use `GraphQLProvider` like this too, but it gives error.  Any suggestion for separation like these?

**Comment by eusdima** [comment]
@hofmannZ you did it for our apps, can you share with him how you did the multi provider?

**Comment by mainawycliffe** [comment]
`GraphQLProvider` is just a widget, which wraps around an inherited widget. This inherited widget is the one that pump down the client to all descendants, so that when you use the `Query` widget, it can access the client from the `GraphQLProvider`. 

One solution i can think of is to pass the client itself:

```dart
MultiProvider(
  providers: [
    Provider<ValueNotifier<GraphQLClient>>.value(value: client),
  ],
  child: someWidget,
)
```

And the either use the dart client or create `GraphQLProvider` Widget at the appropriate location in the widget tree with getting the client from Provider. You can also use the `GraphQLProvider` widget as the direct child of MultiProvider. 

On  a package level, may be we can have something like `QueryWithProvider` widget, that reads the client value from provider instead of the inherited widget, but other behaves the same. I this can be done without breaking anything.

**Comment by jerryzhoujw** [comment]
yes, I use `GraphQLProvider` as child of `MultiProvider` for now,  Thank you @mainawycliffe

**Comment by franzejr** [comment]
Can you guys give a more detailed example on how to use it with `MultiProvider`? Thanks!

**Comment by mainawycliffe** [comment]
@franzejr currently, this library doesn't support `MultiProvider` from provider directly, this is a future we might provide it in the future. For now, the easiest way I can think of is using GraphQLProvider as a child of `MultiProvider`. Something like:

```dart
MultiProvider(
  providers: [
    Provider<Foo>.value(value: foo),
    Provider<Bar>.value(value: bar),
    Provider<Baz>.value(value: baz),
  ],
  child: GraphQLProvider(...),
)
```
