### ISSUE TITLE
Subscription channel

### ISSUE THREAD

**Issue by chenxianqi** [zino-app/graphql-flutter#349]
How can I listen to the contents of the relevant channel?
such as：
RN Library
https://github.com/kesha-antonov/react-native-action-cable
![image](https://user-images.githubusercontent.com/27764334/60333564-f3405080-99cb-11e9-9692-9b8f398dfc57.png)

**Comment by chenxianqi** [comment]
@mainawycliffe
Hey, can you answer my question? Actually, I'm connected to the server, but I don't know how to listen to the data on a particular channel. Thank

**Comment by mainawycliffe** [comment]
Hi, sorry I hadn't come across your question, too many notifications on my inbox. I would like more details to be able to assist you better. But in summary, GraphQL Subscription, are a lot similar to Queries, but use Subscription keyword instead of query. 

For your case, am guessing your query would like:

```graphql
subscription channels($channelId: String!){
  newPost(channelId: $channelId){
    id
    post
    ...
  }
}
```

This will allow you to subscribe to that channel, by channelId. To use the subscription, please check the subscription example [here ](https://github.com/zino-app/graphql-flutter/blob/master/examples/starwars/lib/reviews/review_subscription.dart)(StarsWars example). 

On the server side, your graphql schema would probably look like this:

```
type Subscription {
  newPost(channelId: String!): Posts
}
```

And the back-end implementation is something i can't help you with, without knowing further details, because it will vary from language to language and from library to library. 

And since this libraries is modeled close to apollo-react, you might find their [documentation](https://www.apollographql.com/docs/react/advanced/subscriptions/) about subscription quite helpful.

**Comment by chenxianqi** [comment]
Thanks, it’s a pity that I haven’t solved it yet.

**Comment by mainawycliffe** [comment]
Where are you facing challenges?

**Comment by mainawycliffe** [comment]
This resource could help you understand how subscription can work for you https://hackernoon.com/from-zero-to-graphql-subscriptions-416b9e0284f3
