### ISSUE TITLE
How to clear up the cache??

### ISSUE THREAD

**Issue by anirudhsharma392** [zino-app/graphql-flutter#353]

**Comment by anirudhsharma392** [comment]
if i pop the screen and navigate back to the same screen.Then instead of running the query again it shows me the older results.

**Comment by mainawycliffe** [comment]
Am not sure if it's possible to clear the cache, @micimize would answer this better. But for your case, it seems as if you need live data, not cached data. If this is the case, i would suggest switching to a different fetch policy - `networkOnly` or `noCache`. The first one will fetch the data from the network but cache it while the second one fetches the data from the network and doesn't cache at all.

**Comment by micimize** [comment]
If you're using default network sessions you should see old results briefly, followed by resolved results from the network.

Cache invalidation/TTL is a larger issue - just created [an issue to track it](https://github.com/zino-app/graphql-flutter/issues/354)

**Comment by anirudhsharma392** [comment]
thanks @mainawycliffe  it solves my current issue.

**Comment by bCliks** [comment]
Same issue for me.  @anirudhsharma392 how you fixed?  How did you change the cache & fetch policy. Any code sample?

Thanks

**Comment by beingadrian** [comment]
@bCliks pretty late–I had the same issue initially since the default behaviour was not obvious at the start. You can do so via setting the `fetchPolicy` param on `QueryOptions` which gets passed to the `query` method every time you make a request.

```dart
    final options = QueryOptions(
      document: getHomeContentQuery,
      variables: {
        ...
      },
      fetchPolicy: FetchPolicy.cacheAndNetwork, // change your policy here
    );
```

Figured it out by hovering over `QueryOptions` on VSCode which shows you the default values. Of course, you can explore the open-source code yourself and find the default values there as well.
