### ISSUE TITLE
[Question] How to log response and request?

### ISSUE THREAD

**Issue by amadeu01** [zino-app/graphql-flutter#404]
Like #188 

I was not able to _print_ response of the request because the response is the type of StreamedResponse and it can only be subscribed once, so how do you log the response?

From other projects, https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor
it could be nice to have a small lib/plugin for logging.

**Comment by amadeu01** [comment]
I managed to make a nice logger by implementing my own `BaseClient`

```dart
import 'dart:convert';
import 'dart:developer' as developer;

import 'package:http/http.dart';

class LoggerHttpClient extends BaseClient {
  final Client _client;
  final JsonEncoder _encoder = new JsonEncoder.withIndent('  ');
  final JsonDecoder _decoder = new JsonDecoder();

  LoggerHttpClient(this._client);

  @override
  void close() {
    _client.close();
  }

  @override
  Future<StreamedResponse> send(BaseRequest request) {
    return _client.send(request).then((response) async {
      final responseString = await response.stream.bytesToString();

      String prettyPrint = _encoder.convert(_decoder.convert(responseString));
      final _res = '''
      responseString: $prettyPrint,
      statusCode: ${response.statusCode},
      headers: ${response.headers},
      reasonPhrase: ${response.reasonPhrase},
      persistentConnection: ${response.persistentConnection},
      request: ${response.request.toString()},
      isRedirect: response.isRedirect''';
      developer.log(_res.toString(), name: "http.client");
      return StreamedResponse(ByteStream.fromBytes(utf8.encode(responseString)),
          response.statusCode,
          headers: response.headers,
          reasonPhrase: response.reasonPhrase,
          persistentConnection: response.persistentConnection,
          contentLength: response.contentLength,
          isRedirect: response.isRedirect,
          request: response.request);
    });
  }
}

```

**Comment by sofasurfa** [comment]
@amadeu01 nice example! I found myself using a custom client as well because I wanted my servers to be able to go into maintenance mode (returning status code 503 via NGNIX load balancer), and thus needed a way to let app users know about it. `GraphQLClient` work on 200 only making it challenging to check for server errors unlike with something like REST + `result.context` doesn't include status code unless you run the query through /`graphql` route first on the server. So anyone struggling with this, implement "non-graphql [errors]" logic in your custom httpClient.
