### ISSUE TITLE
How should we maintain this project? 🚀

### ISSUE THREAD

**Issue by arsen** [zino-app/graphql-flutter#420]
I'm just curious if this project is still going to be supported and maintained?
Based on commit logs since a month ago almost no commits are made.

This is a really awesome project it will be sad to see this go.

**Comment by micimize** [comment]
It is maintained as time allows by a handful of contributors, most actively me and @mainawycliffe,  but none of us have the incentives to work on it full time (no monetized app in production, no patreon money, etc). A month isn't really that long for a project nobody is being paid to work on.

I do have an app in development that depends on this project, which is the reason I started contributing, personally, but I haven't had much time to work on it (or `graphql-flutter`) due to work-work.

I also have a [liberapay](https://en.liberapay.com/micimize/), which if it really took off I'd put a lot more time in here, but I don't expect that to happen, especially since I don't push it at all anyhow.

**Comment by micimize** [comment]
@HofmannZ has previously mentioned that he and @eusdima no longer have the time to contribute significantly (They were developing https://www.zinoapp.com/, which I believe this was originally a dependency for).

Pinned to hopefully make things more transparent.

**Comment by serendipity1004** [comment]
@micimize @mainawycliffe I would love to contribute to this package; however, as I have a full time job like everyone else, I could not find time to look over the entire package. If you guys could spend a bit of time briefly explaining how things are organized. I promise to regularly contribute. It would be excellent if we could source some apollo team to contribute to this package but as they have no plan to do so. This package is the only hope in using graphql on flutter so I believe if we could get some directions for diving into the code, collaborators will increase fast.

**Comment by HofmannZ** [comment]
@serendipity1004 You are more than welcome to contribute!

At the moment, we're exploring a way to fund this open-source project 🚀. We created an [OpenColective](https://opencollective.com/graphql-flutter), so we can hopefully cover (some) engineering costs. We're still looking into how we can split the funds fairly. We'd probably need a way to track time/issues/PRs/etc. All suggestions are welcome!

@micimize @truongsinh @mainawycliffe tagging you in here, just to pick your thoughts ;)

**Comment by micimize** [comment]
I personally think that our current status is fine, all things considered.

If someone monetizes an app built with graphql-flutter (or is trying to) they can step up and support/contribute to their key dependency. That's why I started contributing. I just think we should be transparent about that potential necessity
 
Until then, we're doing what we can, but everyone's got their own priorities. Open collective money would be nice, but could introduce more complexity in governance than it's worth. I'm pretty skeptical of OS crowdfunding in general though.

@serendipity1004 I'll try and find some time to add docs etc.

**Comment by truongsinh** [comment]
Also, it depends on what the needs of what to be maintained/developed.

**Comment by serendipity1004** [comment]
how do you guys usually debug plugins? `print` functions don't seem to work on exteneral packages

**Comment by Sewdn** [comment]
I'm willing to contribute to this awesome projects, as soon as time frees up.

Things I will be working on (in this order):

1. PR on existing CacheProvider to avoid inconsistent/incomplete cache (cfr #423 )
2. moving GraphQLClient to Isolate(s). This issue seems critical when trying to persist cache more often and avoid cache loss when app is closed. (cfr #424 )
3. using Moor as an alternative (normalized/optimistic) CacheLayer, removing overhead of encoding cache to json and providing in cache persistence and restoration. (cfr #402 )

**Comment by shafqatevo** [comment]
We're planning to use this package in another open source framework. We're in the early stages of designing the framework. We hope to get involved in addressing the high priority issues here.

@HofmannZ regarding exploring "We're still looking into how we can split the funds fairly. We'd probably need a way to track time/issues/PRs/etc. All suggestions are welcome!" - is there any current best practice around this? Any successful open source project that does this?

**Comment by ronyitc** [comment]
@shafqatevo, @HofmannZ  I found this https://allcontributors.org/. This helps recognising contributors.  It is using by many open source projects and looks solid. Here is the github repo https://github.com/all-contributors/all-contributors

**Comment by shafqatevo** [comment]
@ronyitc unless I am missing something - I was referring to how to fairly split money raised through crowdfunding of open source projects among its contributors. Not something like All Contributors.

**Comment by SanjiKir** [comment]
Hey guys, how it looks like? Do you have any update on the future of this package, are you looking for contributors or something? Because I don't see many commits lately and I am building a project based on graphql, so just wondering how reliable is to use this package :)

**Comment by micimize** [comment]
@SanjiKir Right now I'm focusing on [`built_value`-based code generation](https://github.com/micimize/major) and it's "example" app, but a round of `graphql_flutter` contributions/maintenance is on my near-term personal roadmap.

I'm currently making a concerted effort to do more open source work/[livecoding](https://www.youtube.com/channel/UCj39MVr1fuFtE1eDNXDGJuQ/), with this being one of the projects I'd like to contribute more to. As [I've mentioned in the discord](https://discordapp.com/channels/559455668810153989/559455668814348429/685888813997752324), if this [experiment](https://www.patreon.com/micimize) gains enough momentum I may be able to step up as more of a core maintainer.

I'd also encourage anyone for whom `graphql_flutter` is a key dependency to contribute to the [open collective](https://opencollective.com/graphql-flutter). The reality of software is someone is always paying for development/maintenance, in some way or another.

**Comment by SanjiKir** [comment]
@micimize I've joined to the list of contributors, I know it's not much, probably will start donating more once there will be some movement here :) Hopefully, there will be more people join open collective supporters, looking forwards to new updates and code reviews in this package! Cheers!

**Comment by micimize** [comment]
I'm [taking responsibility][responsibility] for `v4` and maintenance for now. If it [goes well][me], I'll continue on as core maintainer indefinitely, thus solving this ongoing problem

From #608 :
> I've decided to move working on `graphql_flutter` to the top of my [priority queue][queue], particularly working on [`v4`][v4].
>
> To support development please [sponsor me][me] or the [graphql-flutter open collective][oc] if you can.

[queue]: https://github.com/zino-app/graphql-flutter/issues/420#issuecomment-606340132
[v4]: https://github.com/zino-app/graphql-flutter/projects/3
[me]: https://github.com/sponsors/micimize
[oc]: https://opencollective.com/graphql-flutter
[responsibility]: https://github.com/zino-app/graphql-flutter/issues/608#issuecomment-626059225
