### ISSUE TITLE
Don't send Authorization header if token is null

### ISSUE THREAD

**Issue by KammererTob** [zino-app/graphql-flutter#48]
**Describe the bug**
Currently it seems like that the library is sending the Authorization header regardless if the apiToken is set by the user or not. This leads to a header which looks like this: `Authorization: Bearer null`. It might be cleaner to omit the header alltogether if the apiToken is null/undefined.

**To Reproduce**
1. Define the client without "apiToken"
2. Make a request
3. Header is sent as `Authorization: Bearer null`

**Expected behavior**
No Authorization header is sent at all, since there was no intend to authorize

**Comment by LawJolla** [comment]
Thank you for your incredible work!  I'm new to Flutter/Dart, but I've been working with Apollo from the start, so I cannot comprehend the work that's gone into this project.

To go a step further, many APIs will 401 any `Authorization: Bearer ...` because the client claims it has a Bearer token, regardless of the query.

**Comment by LawJolla** [comment]
@HofmannZ you are killing it!  Incredible.

**Comment by HofmannZ** [comment]
@KammererTob & @LawJolla fixed in #36.

To try it out use version `1.0.0-alpha.3` of this package.

**Comment by VladislavRUS** [comment]
HI there! Unfortunately I am facing this issue again - using 4.0.0-beta.5

I was able to add WA similar to this https://github.com/zino-app/graphql-flutter/issues/363#issuecomment-514544107, but it would be nice to have it fixed in sources :)
