### ISSUE TITLE
Time estimation for next stable release

### ISSUE THREAD

**Issue by ryankauk** [zino-app/graphql-flutter#500]
Hey there, was wondering if anyone has an idea on when the next stable release will be? I have issues with subscriptions and another with migration to dart version, both of which are fixed in the beta channel. Tried the beta but there's a lot of breaking changes, was wondering if there's anyway around refactoring my structure.

**Comment by mainawycliffe** [comment]
It's ready and I think we should be ready to release it as version 3.0 due to the breaking changes. We have a migration guide [here](https://github.com/zino-app/graphql-flutter/blob/beta/changelog-v2-v3.md) to assist you in what has changed between 2.0 and 3.0 (current latest beta). We are looking to improve our way of doing things, so that fixes and patches can be released as soon as possible while breaking changes can wait for a major version but that will have to wait until we release version 3.0.

**Comment by mainawycliffe** [comment]
@HofmannZ can we promote the next version to stable?

**Comment by ryankauk** [comment]
Sounds great. Thanks for the info!

**Comment by HofmannZ** [comment]
@mainawycliffe just merge into master. The master branch is built every week to the stable channel.

**Comment by mainawycliffe** [comment]
@HofmannZ I didn't know it's that easy, let me do it right now.

**Comment by HofmannZ** [comment]
@mainawycliffe We should do it via a PR though, just to make sure someone signs of on it.

**Comment by mainawycliffe** [comment]
Yeah, I am just creating the PR at the moment, it will need to reviews if I am not mistaken.

**Comment by mainawycliffe** [comment]
@HofmannZ  Maybe we should also merge master into beta, that part of the pipeline has been failing for some time now.

**Comment by HofmannZ** [comment]
I'll see if I can make that work now, I have a couple minutes
