### ISSUE TITLE
Things already exist in Relay and I miss them

### ISSUE THREAD

**Issue by johnsiu2016** [zino-app/graphql-flutter#519]
**Is your feature request related to a problem? Please describe.**
I am new to flutter but have a background from react, react native and relay. I am confused that there is no library even mentioning Relay. I don't know why people hate Relay because it is actually the best practices everybody should learn. And this is only place that I found that closed to what I expect in flutter.

Here is what I think is the future of UI development.
![image](https://user-images.githubusercontent.com/17636906/71765443-cbf4ae00-2f2f-11ea-9db2-3132a7e5e5ee.png)

What it does is:
- declare all the data you need in every component/widget  
- the fragment will merge with others to form one big query at compile time, typically only one query per screen. Refetch certain fragments when needed.
- generate the type of declared data so that data object is type safe 
- no need to return loading state, the component is suspense 
- no need to return error state, it will catch by error boundary
- normalize the result into cache, 
- subscribe to cache and get notify with just the data you declare
- auto pagination according to this [spec](https://relay.dev/graphql/connections.htm#) ( noted: the name changed to GraphQL Cursor Connections Specification instead of Relay cursor xxx, because it is the best practice! even when you read the one from [Google](https://cloud.google.com/apis/design/standard_methods) They are suggesting the same thing, including the global unique id. in google term, it is the "name" field )

As you can see, with all this done it can completely replace state management. No need to write services, stores file and connecting to your components manually. GraphQL is the future of state management! But I feel a little bit downgrade when I come to flutter where people still struggle to fight with the state management war. Flutter also does not have hooks...

I don't know how many people aware of the above relay-hooks features but I just want more people know about this because it seems like I cannot search the term "relay" in this library. I think graphql communities in flutter should pay more attention to relay. 

This library is great, maybe even better if it could absorb the best things in relay

**Comment by bsr203** [comment]
I used to use relay during the initial days, then they released `relay modern` mostly borrowing from apollo. Since you know relay, I am sure you heard about apollo. This library has similar API like apollo. So, most important features like data colocation etc should be applicable. Some of the difference may stem from the fact that relay is developed by a dedicated team at FB and this library is young and supported by few individuals. error boundary, suspense, hooks etc are relatively new and not necessarily applicable to even flutter. So, play with this library, and study the difference of relay and apollo, and would be great if you can bring some ideas and contribution from relay.  This is my personal remarks.

**Comment by hyochan** [comment]
Really miss relay curor pagination spec which is also in apollo client.

**Comment by satvikpendem** [comment]
I agree, Relay is what the best practices of GraphQL actually are, as you never have to worry about over or underfetching data because every component (or widget, in Flutter's case) outlines exactly what data it needs, then the Relay compiler turns those fragments into one unified query, caching along the way. @johnsiu2016 are you still using graphql_flutter or are there any others that support Relay-style fragment compilation? If no other one supports it, I might submit a PR for a Relay style, or perhaps build my own package if that's out of scope.
