### ISSUE TITLE
Network first cache policy

### ISSUE THREAD

**Issue by p02diada** [zino-app/graphql-flutter#588]
**Is your feature request related to a problem? Please describe.**
Is it possible to have a network-first cache policy? I mean, query request data from network but if there is a connection error because there isn't internet connection it try to get data from cache. 

**Describe the solution you'd like**
A network-first policy cache

**Comment by saarikivit** [comment]
Hey! Would "cache and network" yield desired results?

When loading == true -> render loading.
If the result includes exception -> render from the cache.
If the result includes data -> render from the data.

**Comment by lazylazyllama** [comment]
I think this is somewhat similar to #614 

@saarikivit the problem is, that if the result incluldes a exception the data property is empty and so you can't render from cache. You would have to write an extra query for that with cacheOnly, but that would be really odd I think.

I think it would be best to include the cached data in result even after the failed network fetch. This way you can handle the network error by checking result.exception but still being able to use the cache for your ui.

**Comment by lazylazyllama** [comment]
I figured you have to use `OptimisticCache` to be able to use the cache when the network request fails.

**Comment by Faiyyaz** [comment]
can you provide a sample for it even i am facing the same issue and want the same output

**Comment by micimize** [comment]
Not sure about the right api, but a solution to this problem is a reasonable ask
* [discussion on apollo](https://github.com/apollographql/apollo-client/issues/3755)
* [`apollo-link-network-error`](https://github.com/hollyoops/apollo-link-network-error)

**Comment by micimize** [comment]
In #754 I added `carryForwardDataOnException (default true)` which sets `result.data ??= latestResult.data` when there is an exception. Would this solve the issue here?

**Comment by micimize** [comment]
I think the desired functionality can be achieved now with `4.0.0-beta.4` with `cacheAndNetwork` due to the above:
1. To hide the eager results from the cache before the network result, use `result.source`
2. On network error, the cached data will remain

If there's another consideration I'm not seeing please comment and we'll consider reopening

**Comment by Asquare17** [comment]
@micimize Since PR(https://github.com/zino-hofmann/graphql-flutter/pull/1038) , the logic for `cacheAndNetwork` has been reverted to return cache and then fetch from the network. 
There are good use cases for networkFirstCachePolicy that would try to fetch from the network first and return cache data if there is a network error specifically. Or Is there a way to achieve this currently?

**Comment by micimize** [comment]
@Asquare17 I no longer use or maintain this project, but based on my comment above I was saying the cache-first behavior of `cacheAndNetwork` was still fine for this, because the cached data remained in the result of an exception.

That may have been changed due to a refactor - if so you'll prob want to open a new issue
