### ISSUE TITLE
The graphql client doesn't send request on the second time

### ISSUE THREAD

**Issue by zhaoyi0113** [zino-app/graphql-flutter#645]
I create a graphql client:

```
final HttpLink httpLink = HttpLink(uri: endpoint);
  final AuthLink authLink = AuthLink(getToken: () async {
    Token token = await readToken();
    return token != null ? token.accessToken : '';
  });
  final Link link = authLink.concat(httpLink);
  ValueNotifier<GraphQLClient> client = ValueNotifier(
    GraphQLClient(
      cache: InMemoryCache(),
      link: link,
    ),
  );
```

When I send a query request to backend server, it works and I can see the response looks perfect. However, when I send the query on the second time, it doesn't send the request to the server. Instead, it responses with the previous response data. It seems that it reads data from cache rather than requests to server. My app is online and I am able to connect to internet. 
Is there anything I need to configure in order to stop the client reading from cache?

**Comment by jordychetty** [comment]
All caches implement the abstract base `Cache` which contains the actual structure and mechanisms for performing caching. These are:

- `dynamic read(String key)`
- `void write(String key, dynamic value)`
- `Future<void> save() async`
- `void restore()`
- `void reset()`

You could overwrite the existing entry through custom logic using `write(String key, dynamic value)`. Alternatively, the entries in `InMemoryCache()` themselves are stored in a member called `data`, which is a `dart::collection::HashMap`, so you could invalid the entries by using the `remove()` method when required, although I suppose that the former would be safer.

To the best of my knowledge from browsing through the [caching source code](https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql/lib/src/cache), you are required to implement your own caching strategy that will fulfil your application needs. The project documentation doesn't address this aspect either. 

I encourage anyone more knowledgeable on this to please comment since this is an important topic.

**Comment by micimize** [comment]
You can set the `fetchPolicy` of your `QueryOptions` to skip the cache:
```dart
final QueryOptions options = QueryOptions(
    documentNode: gql(readRepositories),
    variables: <String, dynamic>{
        'nRepositories': nRepositories,
    },
    fetchPolicy: FetchPolicy.networkOnly
);
// ...

final QueryResult result = await _client.query(options);
```
There is also a [`DefaultPolicies`](https://github.com/zino-app/graphql-flutter/blob/eec7d2c5e8d753f7d2d62b2964cb61730caeae42/packages/graphql/lib/src/graphql_client.dart#L14) configuration you can pass to the client. The reason this happens is because the default fetch policy for `query` is `FetchPolicy.cacheFirst`:
https://github.com/zino-app/graphql-flutter/blob/6c188cbb1b287b2c1f7135c41ef4c0f1fe952886/packages/graphql/lib/src/graphql_client.dart#L25-L33

**Comment by jordychetty** [comment]
Oh fantastic! I'll edit my answer now.

**Comment by zhaoyi0113** [comment]
Awesome, thanks
