### ISSUE TITLE
Decouple fetchMore logic from ObservableQuery

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#646]
<details>
<summary>We should extract the fundamentals of <code>fetchMore</code> into a helper function,  so that a <code>QueryResult</code> from <code>client.query</code> can easily be used with it 

</summary

https://github.com/zino-app/graphql-flutter/blob/6c188cbb1b287b2c1f7135c41ef4c0f1fe952886/packages/graphql/lib/src/core/observable_query.dart#L139-L198

</details>

related to #372

**Comment by micimize** [comment]
https://gist.github.com/micimize/cd51edf60d0c3f4cd04c2b78218890f1 is untested, but it should hopefully work for users not using `ObservableQuery`

**Comment by sokolej79** [comment]
Good decision, because now it is only available from client.watchQuery.
And if anybody use only client with own query widgets as I do it is impossible to get fetchMore from     client.query and I don need client.watchQuery for ordinary infinity list scrolling.
Just note aside for flutter Query widget and why I dont use Query widget, it is rebuilding to often.
I think that is because of StreamBuilder<QueryResult>, this line: 
stream=observableQuery.stream
Stream  should not be provided directly to StreamBuilder, that is why it is rebuilding to often. Should be "cached" onInit.

**Comment by micimize** [comment]
resolved in v4 some time ago:
https://github.com/zino-app/graphql-flutter/blob/7192c1669c7dbecff0bbcd0665522c5b41207ab2/packages/graphql/lib/src/graphql_client.dart#L187-L200
