### ISSUE TITLE
Refetch with new Variables? Is it Possible?  

### ISSUE THREAD

**Issue by Mathgobbo** [zino-app/graphql-flutter#668]
Hello, i'm doying an application that has a List (all the data comes by a Query). Can be Applied Filters to the List, and I'd like to Refetch() when submitting the filters, but updating the variables of the Query to the filters that the user chose.
And another question, is it possible to make FetchMore and Refetch with the Subscriptions?

**Comment by vasilich6107** [comment]
Refetch is some kind of an alias for running the same query again which is useful for pull to refresh or other similar cases. If you need to send query with different variables - just fire another query.

**Comment by micimize** [comment]
The `fetchMore` callback should work for your query use case. You can fetchMore with the new variables and replace the results in `updateQuery`.

For subscriptions, `refetch` and `fetchMore` don't make conceptual sense because any new data will be added to the stream in realtime anyways, but you're probably wanting a way to:
1. Accumulate subscription results into a collection
2. Carry accumulated results from the old subscription over in the event of variable change (say, if you're subscribing to changes from a paging query)

In v4 alpha I made a simple [`ResultsAccumulator`](https://github.com/zino-app/graphql-flutter/blob/modularization/packages/graphql_flutter/lib/src/widgets/result_accumulator.dart) widget for use with `Subscription`:
https://github.com/zino-app/graphql-flutter/blob/645d462a73047910ba3c45a1b28483016c082131/examples/starwars/lib/reviews/review_subscription.dart#L31-L36

Might be useful or a good reference for coming up with your own solution. There's a lot of cool higher order abstraction potential with subscriptions, like [apollo's `subscribeToMore`](https://www.apollographql.com/docs/react/data/subscriptions/#subscribetomore), etc. But it will probably be some time before we can implement them in the core lib.

Closing this for now, but feel free to come by [`#support` in the discord](https://discord.gg/tXTtBfC) to talk more about it
