### ISSUE TITLE
[QUESTION] - How to do a token refresh?

### ISSUE THREAD

**Issue by brenoasm** [zino-app/graphql-flutter#672]
Hi, I've been using It to build an personal project and finding hard to implement a refresh process. Using Dio I can block the client so all the subsequence requests goes to a queue and then after unlock the queue is processed. Using graphql_flutter do I need to implement something like that by myself?  If someone has some example to show me. Thanks in advance.

**Comment by Gujie-Novade** [comment]
The way I did was:
When you configure the `AuthLink` like in the doc, do something like:

```dart
final AuthLink authLink = AuthLink(
    getToken: () async  {
       final token = await getAccessToken();
       return `Bearer $token`
    },
  );
```

And the `getAccesstoken()` function does the following:
1. retrieve the access token from wherever you stored it
2. parse it and check the expiry
2.a if it's expired, renew it by making a HTTP call to your server with your refresh token
3. return the access token

**Comment by micimize** [comment]
@brenoasm we don't have an offline operation queue implemented in core (for `AuthLink` or otherwise), and I haven't seen any elsewhere either.

**Comment by brenoasm** [comment]
@Gujie-Novade Cool, what happen's If multiple requests are sent with the invalid token? All the requests pass by the getToken?

@micimize Sorry for the question, but I'not expert using Apollo. Would not be the case to implement such routine? Dio for example has It built in (I mean the queue and way to lock and unlock the client), os it not usefull while using graphql? I did the queue process in my application after I've posted this question, It works but i'm not sure if It is the right way to do.

**Comment by micimize** [comment]
@brenoasm The client doesn't have any awareness of the relatedness of the failures, so unless you set a flag in your code based on an auth error it will continue along as normal.

It'd definitely be useful, but is just non-trivial. A more complicated offline queue is desirable for even more reasons in graphql (#201)

You could make a custom [AuthLink](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/link/auth/link_auth.dart) with refresh state/logic that waits to call `forward` until the new token is gotten. If you  go that route I'm sure it'll be quite use useful to others. It looks like there's some discussion/potential solutions for retry logic in #220 as well

Idk how useful this is but on the v4 alpha we use `gql_link`s, for which there is a [`dio` link](https://github.com/TarekkMA/gql_dio_link).

**Comment by brenoasm** [comment]
Thanks for the response! I did the retry logic inside a custom link, like you said. I was not aware about the v4 and If It let me use an Dio as client, for sure all about I said is built in. I'll close this issue.

**Comment by Aristidios** [comment]
> And the `getAccesstoken()` function does the following:
> 
> 1. retrieve the access token from wherever you stored it
> 2. parse it and check the expiry
>    2.a if it's expired, renew it by making a HTTP call to your server with your refresh token
> 3. return the access token



Hello, 

Would you mind sharing your implementation of `getAccesstoken()` 🙂

@Gujie-Novade

**Comment by x-ji** [comment]
I searched around on the issue of how to handle multiple requests trying to refresh the token at the same time. Using the interceptor from `dio` (with `gql_dio_link`) seems to be a common solution, but it involves a lot of custom code. I saw somebody mention the [`queue`](https://pub.dev/packages/queue) library in one of the discussion https://github.com/cfug/dio/issues/590#issuecomment-900942965, which turned out to be exactly what I need. I made it work with the built-in `AuthLink` by making use of a queue within the `getToken` function, so that if the later calls in the queue realize that the token has already been refreshed by the first call in the queue, they don't try to refresh it again.

(`dio` seems to have introduced a similar idea with `QueuedInterceptor`, but with this `queue` I can work with `graphql_flutter` directly without needing to resort to `dio`.)
