### ISSUE TITLE
Question about how v4 cache works

### ISSUE THREAD

**Issue by rwrz** [zino-app/graphql-flutter#739]
hey @micimize, I have a question about how the cache works. 
Considering a schema like this:
```graphql
type Animal {
    name: String
}
type Furniture {
    name: String
}

query {
    animals() : [Animal]
    furnitures() : [Furniture]
}
```

If I **`watchQuery` `animals { name }` in one widget** and then on **another I `watchQuery` `furnitures { name }`**. 

Then I **`mutate` an `animal`**, the query on **furniture refreshes** as well (even if **nothing changed on furniture**).

Is that correct?
I mean, shouldn't the cache updates only the queries that are related to the mutation data or even when I query another thing, all queries are refreshed.

On my project, I had added a layer to check if the data is really changing before allowing or processing it.

thank you!

**Comment by micimize** [comment]
@rwrz right – theoretically we could track the data dependencies of each watched operation, and only update those, that work just hasn't been done. I'm guessing that's what apollo does, I haven't looked carefully in to how though
> On my project, I had added a layer to check if the data is really changing before allowing or processing it.
I'm curious as to where you're doing this / why you need to? I did consider doing something like
```dart
// loose code
newData = cache.read(query.options.asRequest);
if(!deepEquals(query.lastResult.data, newData)){
  query.addResult(QueryResult(newData))
}
```
But felt that, since query listeners should be reactive already, and thus shouldn't be doing particularly complicated work with each independent result, the cost of doing the deep equals would be greater than whatever downstream operations are done.

For example, a `Query` component at the same point in the tree with the same data passed to the builder should return the same widget tree from `build`, and thus not need to rerender.

**Comment by rwrz** [comment]
> For example, a Query component at the same point in the tree with the same data passed to the builder should return the same widget tree from build, and thus not need to rerender.

You are right... but usually, we transform the `result.data` map into a DTO or something. Or even, do some calculations to transform into a ViewModel somehow. These calculations can be expensive and reduce app performance after a few widgets. And since the GraphQL nature is to have several small widgets, querying the cache simultaneously on the same screen, a little "toggle" instead of the build just the `toggleWidget`, will be building all widgets on the tree that has `Query`, which goes against Flutter or Apollo ideas.. rs

> But felt that, since query listeners should be reactive already, and thus shouldn't be doing particularly complicated work with each independent result, the cost of doing the deep equals would be greater than whatever downstream operations are done.

I have done some tests here and the cost of a deepEquals (`DeepCollectionEquality`) on query data maps, totally worth it. Are just a few milliseconds or even nanoseconds... But I can take a look at what Apollo is doing right now, but I believe it is something more related to the Fragments, like subscribing to Query fragments changes... instead of comparing results.

**Comment by micimize** [comment]
@rwrz well for now, if you have a function for filtering `QueryResults` based on a deep equal check, then you could add a `class extension` to `ObservableQuery` that wraps `listen` in your deduplicator. A more integrated flag is something we can consider adding after the first `beta` release

**Comment by rwrz** [comment]
Sure. Great idea.
And thank you for your time! =)
