### ISSUE TITLE
What is the idFields in the FragmentRequest?

### ISSUE THREAD

**Issue by GP4cK** [zino-app/graphql-flutter#808]
I don't understand the docs on `readFragment()`. What is idFields.id?

Here's the current doc:
```dart
final fragmentDoc = gql(
  r'''
    fragment mySmallSubset on MyType {
      myField,
      someNewField
    }
  ''',
);

var fragmentRequest = FragmentRequest(
  fragment: Fragment(document: fragmentDoc),
  idFields: {'__typename': 'MyType', 'id': 1}, // <- what is this?
);

final data = client.readFragment(fragmentRequest);
client.writeFragment(fragmentRequest, data);
```

For example, assuming my query is like this:
```graphql
query projectItemsCount($projectID: String!) {
  projectItemsCount(projectID: $projectID) {
    ...FormsCount
  }
}

fragment FormsCount on ProjectItemsCount {
  forms
}
```
How should I build my FormFragmentRequest?

**Comment by geisterfurz007** [comment]
I believe the id fields are the ones used in the dataIdFromObject function of your GraphQLCache so the cache can create a proper entry for it. The default implementation uses the `__typename` and `id` fields so it makes sense to use them in the example. If at least one of them is missing, the default implementation returns null and (by my understanding, take this one with a grain of salt) no cache entry is created.

As to what you should use for your query/fragment: It depends on what fields you use to get a dataId. If you haven't implemented a custom `dataIdFromObject` function, you want to supply it with `__typename` and `id` of your `ProjectItemsCount` entity so it can look up the correct entry in the cache. If you have a custom implementation, pass a map with all values needed to generate the id properly.

**Comment by nephix** [comment]
Probably the same as in Apollo's [`readFragment`](https://www.apollographql.com/docs/react/caching/cache-interaction/#readfragment)

**Comment by GP4cK** [comment]
Thanks a lot for helping.
I tried using the `dataIdFromObject` but it seems to never get called:
```dart
GraphQLClient(
  cache: GraphQLCache(
    dataIdFromObject: (object) {
      print('dataIdFromObject'); // Nothing ever gets printed
    },
  ),
  link: link,
)
```
Is it correct to say that this function is called every time you make a query (using the [Query](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql_flutter/lib/src/widgets/query.dart) widget or cache.readQuery)? Or am I supposed to write in the cache myself when I get the result from a query?

Also, I saw that `dataIdFromObject` is marked as deprecated in the [docs](https://www.apollographql.com/docs/react/caching/cache-configuration/#configuration-options). So I added [normalize](https://pub.dev/packages/normalize) in my pubspec to be able to use a TypePolicy. I then tried this code too but nothing ever gets printed:
```dart
GraphQLClient(
  cache: GraphQLCache(
    typePolicies: {
      'ProjectItemsCount': TypePolicy(
        fields: {
          // Not sure what to use as keys so I tried both FormsCount and forms
          'FormsCount': FieldPolicy(read: (_, __) => print('read')),
          'forms': FieldPolicy(read: (_, __) => print('read')),
        },
      )
    },
  ),
  link: link,
),
```

Here's an extract from my schema:

```graphql
type ProjectItemsCount {
  forms: Int!
  # ...
}

type Query {
  projectItemsCount(projectID: String!): ProjectItemsCount!
  # ...
}
```

**Comment by micimize** [comment]
geisterfurz007's explanation was correct – `idFields` is separate from `data` because the data might not contain the relevant fields. Because [`readFragment`](https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql#fragmentrequest-readfragment-and-writefragment)'s API is a pass-through for the normalize's [`normalizeFragment`](https://pub.dev/documentation/normalize/latest/normalize/normalizeFragment.html), you can look there for more details. 

@GP4cK – `dataIdFromObject` may be deprecated by apollo, but is not deprecated for us. I would have to see the actual `Query / client.query / client.watchQuery` code, data returned from the server, and cache state (`cache.store.toMap()`) to know why `dataIdFromObject`, etc wasn't being called.

I did discover a dumb issue with `cache.readQuery` that I [just hotfixed](https://github.com/zino-app/graphql-flutter/commit/000d59ff2dd6b508ec132fb8712ba1fe68211ba6#diff-252f4a0c47482310ec1c6b60baf7126616c2018b2f663e20745d17d29d504fa0L86-R86) in `4.0.1`, but you should still be seeing ` print('dataIdFromObject')` when using a cache-enabled `Query` because of the `writeQuery` call. Cache writes are controlled by [`fetchPolicy`](https://pub.dev/documentation/graphql/latest/graphql/FetchPolicy-class.html).


Depending on what you're trying to do, you might be better off doing a `client.readQuery` `client.writeQuery` round trip with the `projectItemsCount` query, updating the nested data structure. `writeFragment` is meant for updating fields of normalized data, which is why there's typically an `id` field, but your query result looks more like an aggregate with no fixed identity.

**Comment by GP4cK** [comment]
I ended up using client.writeQuery, it was easier.
Thank you very much for you help, all of you!

**Comment by SalahAdDin** [comment]
> I ended up using client.writeQuery, it was easier.
> Thank you very much for you help, all of you!

How did you solve it? Can you share it with us?
