### ISSUE TITLE
Query widget Builder execute 2 or 3 times for each request

### ISSUE THREAD

**Issue by pokapow** [zino-app/graphql-flutter#810]
When I execute a certain request with the Query widget from v4 of graphql_flutter, the request execute 2 or 3 times:

![image](https://user-images.githubusercontent.com/30467320/106949712-9cfdcc80-672d-11eb-80e2-27649715b040.png)

Here we see the `I'M HERE 2 !` print executed 3 times just for one call to this query.
But the `I'M HERE 1` executed just one time, as exepected.

1. Clone [this repo](https://git.p2p.legal/axiom-team/gecko) from master and launch it with VSCode
2. Paste a Ğ1 publickey (as this one for example: D2meevcAHFTS2gQMvmRW5Hzi25jDdikk4nC4u1FkwRaU) on "Tappez/collez une clé publique, ou scannez" placeholder of TextField on Home view.
3. See the result in debug console on VSCode.  ([this line in code](https://git.p2p.legal/axiom-team/gecko/src/branch/master/lib/screens/history.dart#L106))

**Expected behavior**
This request should execute only one time, not 2 or 3.

**Smartphone (please complete the following information):**
 - Device: [Pixel 4]
 - OS: [Android]
 - Version [10 (SDK 29)]

**Comment by geisterfurz007** [comment]
Slightly incorrect. The *builder* executes several times, the request does not (you can check the network tab of the Flutter devtools to verify only one request is sent). The build executes each time the status changes (for example from loading to not loading because the request is completed).

You can check that by moving the print below the if statement starting in L108 in your screenshot to not print when it's loading and only when you have data.

Now even then it can happen that the print appears more than once. This is because the Query widget uses the fetchPolicy `cacheAndNetwork` by default ([here](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql_flutter/lib/src/widgets/query.dart#L42) you can see `client.watchQuery` being called which is [here](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql/lib/src/graphql_client.dart#L92) which uses the default policies for watchQueries defined [here](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql/lib/src/core/policies.dart#L260)). That means that it will first set the result to loading (I believe), then send the network request, while that is going look in the cache if a matching result there already. If there is, the builder function is called with that. Then, once the network request returns a valid result, the builder function is called once *more* with the updated result from that.

That would result in a total of 3 calls (first call with loading, second call with cache result, third call with network result) which matches your output.

You can check if that is actually the case by also printing `result.source.isEager` (from the docs: 'Whether this result source is considered "eager" (is cache or optimisticResult)').

**Comment by pokapow** [comment]
Thank you @geisterfurz007 for your explanations.
I discovered the network view of the Flutter devtools thanks to you, and indeed the request to be executed only once, as expected.

I still have a hard time understanding this behavior but I will dig it.
Thank you very much for your time and your work.
